//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_default p__default;
        
        private static SteamVR_Input_ActionSet_mixedreality p_mixedreality;
        
        private static SteamVR_Input_ActionSet_RightJoystick p_RightJoystick;
        
        private static SteamVR_Input_ActionSet_LeftJoystick p_LeftJoystick;
        
        public static SteamVR_Input_ActionSet_default _default
        {
            get
            {
                return SteamVR_Actions.p__default.GetCopy<SteamVR_Input_ActionSet_default>();
            }
        }
        
        public static SteamVR_Input_ActionSet_mixedreality mixedreality
        {
            get
            {
                return SteamVR_Actions.p_mixedreality.GetCopy<SteamVR_Input_ActionSet_mixedreality>();
            }
        }
        
        public static SteamVR_Input_ActionSet_RightJoystick RightJoystick
        {
            get
            {
                return SteamVR_Actions.p_RightJoystick.GetCopy<SteamVR_Input_ActionSet_RightJoystick>();
            }
        }
        
        public static SteamVR_Input_ActionSet_LeftJoystick LeftJoystick
        {
            get
            {
                return SteamVR_Actions.p_LeftJoystick.GetCopy<SteamVR_Input_ActionSet_LeftJoystick>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p__default = ((SteamVR_Input_ActionSet_default)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_default>("/actions/default")));
            SteamVR_Actions.p_mixedreality = ((SteamVR_Input_ActionSet_mixedreality)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_mixedreality>("/actions/mixedreality")));
            SteamVR_Actions.p_RightJoystick = ((SteamVR_Input_ActionSet_RightJoystick)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_RightJoystick>("/actions/RightJoystick")));
            SteamVR_Actions.p_LeftJoystick = ((SteamVR_Input_ActionSet_LeftJoystick)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_LeftJoystick>("/actions/LeftJoystick")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions._default,
                    SteamVR_Actions.mixedreality,
                    SteamVR_Actions.RightJoystick,
                    SteamVR_Actions.LeftJoystick};
        }
    }
}
